### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by habbahab** [Microsoft/MCAS#45]
Hi,

I tried your scripts today, but I got the error: "Invoke-MCASRestMethod2 : Unknown exception when attempting to contact the Cloud App Security REST API: {"detail":"Invalid token"}" no matter what command I tried.
After looking at the script i found out that the "Select-MCAStoken" function did a .ToLower() method on the token when it fetches it from the credential object, and that breaks the token as it is case sensitive.

Br.
Hans-Arne Bjella

**Comment by powershellshock** [comment]
We haven't been using Invoke-MCASRestMethod2 in some time, so you appear to be using an outdated version of the module.  Remove all versions of the module from your system and install the latest version via: 
`Install-Module -Name MCAS`
