### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by nemws1** [microsoft/MCAS#57]
Looks like Microsoft is forcing TLS 1.2 on the MCAS API, but PowerShell still tries to negotiate TLS 1.0 with the standard Invoke-RestMethod.  I've been getting this error, starting yesterday:

```
Error calling MCAS API. The exception was: The request was aborted: Could not create SSL/TLS secure channel.
At C:\Program Files\WindowsPowerShell\Modules\MCAS\3.3.0\Functions\Get-MCASAlert.ps1:219 char:17
+                 throw "Error calling MCAS API. The exception was: $_"    
```

I was able to get my scripts working again by editing Invoke-MCASRestMethod.ps1 and adding this on line 55 (perhaps not the correct spot for this):

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;`

(Found at: https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel)

Not sure if this is a group policy issue at my workplace or something this is affecting everybody.

PS - Love this module! Thank you for all your hard work on it! :)

**Comment by Javanite** [comment]
Thanks for the great feedback! I can confirm that this does not appear to be an issue affecting most other users, however, I would tend to agree that we should force TLS 1.2 just in case there are users who do not have 1.2 set as their system default.

I will add  `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;`  to Invoke-McasRestMethod, create a PR, and chat with Jared to validate there are not any problems. I'll leave this issue open until we do our next publish into the PS Gallery.

**Comment by nemws1** [comment]
MS did release an article on this:

https://techcommunity.microsoft.com/t5/Enterprise-Mobility-Security/End-of-support-for-TLS-1-0-and-1-1-in-Microsoft-Cloud-App/ba-p/770507
