### ISSUE TITLE
New-MCASSubnetCollection -tags parameter issue

### ISSUE THREAD

**Issue by k2c-dev** [microsoft/MCAS#72]
Hello,

when I execute New-MCASSubnetCollection with tags parameter then it creates always new tag with same name but with different tag _id number and it is not using already created tag. Then I have multiple times same tag name in CAS env. and under the tag I have only 1 subnet or IP.

![image](https://user-images.githubusercontent.com/58179126/80598451-aaad5580-8a29-11ea-9bc1-fd89829f2a9c.png)

Another question. How I can remove the duplicates? 
![image](https://user-images.githubusercontent.com/58179126/80598741-18f21800-8a2a-11ea-8c0c-162ce32b6750.png)

**Comment by Javanite** [comment]
Hi @k2c-dev,

The New-MCASSubnetCollection cmdlet is designed only create new subnet collections, not update existing collections. I agree that this would be a nice to have a cmdlet for subnet editing, so I'll add that to my backlog.

As for removing duplicates, you can use Remove-MCASSubnetCollection with the ID of the subnet you want to remove.

`Remove-MCASSubnetCollection -Identity '5a9e04c7f82b1bb8af51c7fb'`

**Comment by k2c-dev** [comment]
Hello Javanite,
yes I know about the Remove-MCASSubnetCollection but it is not the issue. The issue is with TAGs. When you execute New-MCASSubnetCollection with -tags parameter then it is creating always the new tag but with same name.

Example
I have already tag VPN in MCAS environment.
Then I execute: New-MCASSubnetCollection....... - tags "VPN"
The result is that I have 2 tags with name VPN. Each has different _id number.

When there is already tag VPN it should associate it to existing one and not to create duplicates.
