### ISSUE TITLE
Discovered apps

### ISSUE THREAD

**Issue by SquirrelAssassin** [microsoft/MCAS#73]
When we pull back discoveredapps the tags never show sanctioned, unsanctioned, or none, only watching?  Is this possible?  Really we want to just find discovered apps that have been used and with tag none.

**Comment by Javanite** [comment]
> When we pull back discoveredapps the tags never show sanctioned, unsanctioned, or none, only watching? Is this possible? Really we want to just find discovered apps that have been used and with tag none.

Hi SquirrelAssassin - Unfortunately, it does not appear that the data returned from the service contains Sanctioned/Unsanctioned tags, but you can use the -Tag operator for Get-MCASDiscoveredApp to only retrieve apps with either of those tags. As for the "None" tag, I did not originally include it in the module, but I will add it in v3.3.6 soon.

Example of using the Tag operator:
`Get-MCASDiscoveredApp -StreamId 5c45cf5a78ccffdd8e99bb8a -Tag Sanctioned`

Once I publish 3.3.6 to the PS gallery I will update this issue.

**Comment by SquirrelAssassin** [comment]
for now this worked, also got around the 100 return limit

#get initial string
$count = 0
$array=@()
$body = @{
    'skip'=$count
    'filters' = @{"tag"=@{"eq"=@("None")}}
    'entityType'="service"
    'performAsyncTotal'="false"
}
$response = Invoke-MCASRestMethod -Credential $mcasCred -Path "/cas/api/v1/discovery/discovered_apps/" -Method Post -Body $body
write-host "the count is $($count)"
foreach ($item in $response.data) {
    if (($item.name -ne "GTmetrix") -and ($item.name -ne "Paragon Protect & Restore") -and ($item.name -ne "Lanka Host Web Hosting Network")){
        $array += $item
    }
}
$total = $response.total
write-host "total items found in the results $($total)"

#loop through and get the rest
if ($response.hasNext -eq $true) {
    do
    {
        $count += 100
        $body = @{
            'skip'=$count
            'filters' = @{"tag"=@{"eq"=@("None")}}
            'entityType'="service"
            'performAsyncTotal'="false"
        }
        $response = Invoke-MCASRestMethod -Credential $mcasCred -Path "/cas/api/v1/discovery/discovered_apps/" -Method Post -Body $body
        foreach ($item in $response.data) {
            if (($item.name -ne "GTmetrix") -and ($item.name -ne "Paragon Protect & Restore") -and ($item.name -ne "Lanka Host Web Hosting Network")){
                $array += $item
            }
        }
        write-host "response total is $($response.total)"
        write-host "the count is $($count)"
        write-host "is there more to pull back? $($response.hasnext)"
    }
    until ($response.hasnext -eq $false)
}
write-host "total items that need to be addressed $($array.count)"

$apps = $array | group-object -Property appid

**Comment by SquirrelAssassin** [comment]
For whatever reason "GTmetrix", "Paragon Protect & Restore", and "Lanka Host Web Hosting Network" show up from the API but is no where to be found from the portal.

**Comment by Javanite** [comment]
@SquirrelAssassin Could you do me a favor and pull data on those apps and check the "lastUsed" property and see if the date somewhere in early March?

**Comment by SquirrelAssassin** [comment]
I can tell you what happened, the streamid didn't make sense to me until I figured out that it correlated back to the connectors we had to mcas.   Once I switched from "global" to "win10 endpoint users", I could see in the webpage request the streamid wasnt related to the app that was flagged.

**Comment by SquirrelAssassin** [comment]
I cheated a little bit and took the easy road on on the users and apps that were accessed by only grabbing the first item from the group so shame on me but for my use case its really just a pointer for a SharePoint list for someone to go take a look at the real discovered app.

$count = 0
$array=@()
$body = @{
    'skip'=$count
    'filters' = @{"tag"=@{"eq"=@("None")}}
    'entityType'="service"
    'performAsyncTotal'="false"
}
$response = Invoke-MCASRestMethod -Credential $mcasCred -Path "/cas/api/v1/discovery/discovered_apps/" -Method Post -Body $body
foreach ($item in $response.data) {
        $array += $item
}
$total = $response.total
write-output "total items found in the results $($total)"

#loop through and get the rest
if ($response.hasNext -eq $true) {
    do
    {
        $count += 100
        $body = @{
            'skip'=$count
            'filters' = @{"tag"=@{"eq"=@("None")}}
            'entityType'="service"
        }
        $response = Invoke-MCASRestMethod -Credential $mcasCred -Path "/cas/api/v1/discovery/discovered_apps/" -Method Post -Body $body
        foreach ($item in $response.data) {
                $array += $item
        }
        write-output "response total is $($response.total)"
        write-output "the count is $($count)"
        write-output "is there more to pull back? $($response.hasnext)"
    }
    until ($response.hasnext -eq $false)
}
write-output "total items that need to be addressed $($array.count)"

write-output "4"

# time to get the info for each of the apps with none set as the tag
$apps = $array | group-object -Property appid
$finalarray = @()
foreach ($finds in $apps) {
    # get first user and IPthat accessed this app
    $body1 = @{
            'skip'=0
            'filters' = @{}
            'appId'=$($finds.group[0].appId)
            'streamId'=$($finds.group[0].streamId)
        }
    
    # get user
    $response = Invoke-MCASRestMethod -Credential $mcasCred -Path "/cas/api/v1/discovery/app_users/" -Method Post -Body $body1
    # get ip of user
    $response1 = Invoke-MCASRestMethod -Credential $mcasCred -Path "/cas/api/v1/discovery/app_ips/" -Method Post -Body $body1

    #get machine name based on ip
    $body2 = @{
            'skip'=0
            'filters' = @{"ip.entity"=@{"eq"=@("$($response1.data[0].name)")}}
            'appId'=$($finds.group[0].appId)
            'streamId'=$($finds.group[0].streamId)
        }
    $response2 = Invoke-MCASRestMethod -Credential $mcasCred -path "/cas/api/v1/discovery/ip2machine/" -Method Post -Body $body2
    
    #additional informatoin
    $names = "User: $($response.data[0].name)"
    $ip = "User IP: $($response1.data[0].name)"
    $machine = "User Possible Machine(s): $($response2.data[0].entityValues)"
    $hqlocation = "Headquarters: $(if (!$finds.group[0].hqLocation) {write-output "Unknown"} else {write-output $finds.group[0].hqLocation}) "
    $firstused = "First used: $($finds.group[0].firstUsed | get-date)"
    $domains = "All Domains: $finds.Group.alldomains"

    # join all the additional info in and use some html to split it up for sharepoint
    $addinfo = "$domains <br> $names <br> $ip <br> $machine <br> $hqlocation <br> $firstused"

    #add findings to array
    $finalarray += [pscustomobject] @{
        AppName = $finds.group[0].name
        AppCategory = ($finds.group[0].category).Replace('SAASDB_CATEGORY_','').replace('_',' ')
        AppScore = [math]::Round($finds.group[0].revised_score.total)
        Reviewer = $approver
        AdditionalInformation = $addinfo
    }
write-output $finds.group[0].name
}
