### ISSUE TITLE
Get-MCASActivity does not work

### ISSUE THREAD

**Issue by hirosh-takayama** [microsoft/MCAS#74]
When I run the Get-MCASActivity cmdlet, I get the following error message:
The version is 3.3.4. Other modules can be used.

404Page not found

/////////
Invoke-WebRequest : var __ADALLOM_CONSTS = {
  CONSOLE_VERSION: '0.176.221',
  ADALLOM_USER: "",
  USER_HASH: "",
  ADALLOM_TENANT_ID: 103222650,
  FULL_LOCALE: 'en-US',
  LOCALE: 'en',
  SERVER_URL: '',
  CONSOLE_CDN_URL: 'https://cdn.cloudappsecurity.com/console/0.176.221/',
  I18N_CDN_URL: 'https://cdn.cloudappsecurity.com/i18n/0.176.180/',
  DATA_CENTER_NAME: 'US3',
  REGION_NAME: 'West US 2',
  SERVER_DOMAIN: '',
  USING_GATEWAY: false,
  DELETE_COOKIE_ON_SWITCH: false,
  I18N_LOCALES: ['en-US'],
  AGGREGATED_ENVIRONMENT_DATA: JSON.parse(JSON.stringify('' || '{}')),
  IS_INVITED_ADMIN: false,
  IS_AAD_LOGIN: false,
  CONSOLE_LOG_LEVEL: 2,
  APP_INSIGHTS_KEY: '01f17a1d-bef5-4bfd-ba5b-e3588d4c2e15',
  MS_FLOW_URL: 'https://flow.microsoft.com/',
  ATP_PORTAL_BASE_URL: 'https://portal.atp.azure.com/',
};404Page not foundIf the problem persists, contact support.Go to dashboard
発生場所 行:1 文字:1
+ Invoke-WebRequest -Uri 'https://csec4nulg.us3.portal.cloudappsecurity ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]、WebExce
    ption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by k2c-dev** [comment]
Hi, same issue for me!

**Comment by o13d** [comment]
Hi, I encounter same problem since yesterday 6/2/2020

**Comment by Javanite** [comment]
_Hi All - Thank you for reporting this and apologies for the delays on other issues. Wife and I just had a new baby and have been off on leave. I'll do my best to get through all outstanding issues._ 

I have identified the issue and pushed a fix to the PS Gallery. Please uninstall version 3.3.4 and download the latest version (3.3.5).

**Comment by hirosh-takayama** [comment]
Hi Javanite  - Thank you for your prompt response!  Get-MCASActivity module was used normally.

**Comment by o13d** [comment]
Thank you very much for the support.
